import type { Customer } from "./types";

type MockSeed = Omit<Customer, "dn" | "logIds" | "scheduleIds"> &
  Partial<Pick<Customer, "dn" | "logIds" | "scheduleIds">>;

const today = new Date();
function ago(days: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() - days);
  return d.toISOString().slice(0, 10);
}
function ahead(days: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

const RAW_MOCKS: MockSeed[] = [
  {
    id: "m1",
    name: "박태윤",
    phone: "010-2841-7733",
    stage: "first_contact",
    stageRaw: "첫컨택",
    heat: "warm",
    rank: "B",
    grade: "A",
    salesStatus: "잠재고객",
    vehicleClass: "GLE-Class",
    vehicleInterest: "GLE 450 4MATIC",
    budget: "1.4~1.6억",
    criticalFactor: "법인 명의 / 사이즈",
    source: "구글폼",
    channel: "유튜브",
    age: "40대",
    gender: "남",
    firstContact: ago(0),
    nextContact: ahead(1),
    notes: "법인 차량 검토. 사이즈 우선.",
  },
  {
    id: "m2",
    name: "이서연",
    phone: "010-9921-4408",
    stage: "first_contact",
    stageRaw: "첫컨택",
    heat: "hot",
    rank: "A",
    grade: "A",
    salesStatus: "잠재고객",
    vehicleClass: "E-Class",
    vehicleInterest: "E300 4MATIC Exclusive",
    budget: "9,500만",
    criticalFactor: "이번달 출고 가능 여부",
    source: "카톡채널",
    channel: "고객소개",
    age: "30대",
    gender: "여",
    firstContact: ago(2),
    nextContact: ago(0),
    notes: "프로모션 문의 — 빠른 출고 희망.",
  },
  {
    id: "m3",
    name: "정현우",
    phone: "010-3372-1190",
    stage: "fu_1",
    stageRaw: "1st F/U",
    heat: "warm",
    rank: "B",
    grade: "VIP",
    salesStatus: "잠재고객",
    vehicleClass: "S-Class",
    vehicleInterest: "S580 4MATIC Long",
    budget: "2.0억",
    criticalFactor: "법인 vs 개인",
    source: "전화·문자",
    channel: "기존",
    age: "50대",
    gender: "남",
    firstContact: ago(7),
    nextContact: ahead(2),
    exteriorColor: "셀레나이트 그레이",
    notes: "1차 상담 — 후속 자료 요청, 리스 견적 비교 진행 중.",
  },
  {
    id: "m4",
    name: "최유진",
    phone: "010-1188-2370",
    stage: "fu_2",
    stageRaw: "2nd F/U",
    heat: "cold",
    rank: "C",
    grade: "B",
    salesStatus: "잠재고객",
    vehicleClass: "EQE",
    vehicleInterest: "EQE 350 4MATIC",
    budget: "1.2억",
    competitor: "Tesla Model S",
    source: "오픈채팅",
    channel: "유튜브",
    age: "40대",
    gender: "여",
    firstContact: ago(20),
    nextContact: ago(1),
    notes: "1주 무응답. 식어가는 중.",
  },
  {
    id: "m5",
    name: "강지현",
    phone: "010-7752-3098",
    stage: "decision",
    stageRaw: "의사결정",
    heat: "hot",
    rank: "A",
    grade: "A",
    salesStatus: "잠재고객",
    vehicleClass: "GLC-Class",
    vehicleInterest: "GLC 300 4MATIC Coupe",
    budget: "9,200만",
    criticalFactor: "BMW X3 비교 클로징",
    competitor: "BMW X3 30i",
    source: "구글폼",
    channel: "블로그",
    age: "30대",
    gender: "여",
    firstContact: ago(14),
    nextContact: ahead(5),
    exteriorColor: "폴라 화이트",
  },
  {
    id: "m6",
    name: "윤태영",
    phone: "010-4408-5511",
    stage: "decision",
    stageRaw: "의사결정",
    heat: "warm",
    rank: "B",
    grade: "VIP",
    salesStatus: "잠재고객",
    vehicleClass: "CLE-Class",
    vehicleInterest: "CLE 53 Cabriolet AMG",
    budget: "1.5억",
    source: "전화·문자",
    channel: "재구매",
    age: "40대",
    gender: "남",
    firstContact: ago(10),
    nextContact: ahead(4),
    notes: "시승 후 골든타임 7일 카운트.",
  },
  {
    id: "m7",
    name: "한도윤",
    phone: "010-6629-4471",
    stage: "contract",
    stageRaw: "계약진행",
    heat: "hot",
    rank: "A",
    grade: "A",
    salesStatus: "계약고객",
    vehicleClass: "E-Class",
    vehicleInterest: "E200 Avantgarde",
    budget: "8,500만",
    criticalFactor: "트레이드인 가격",
    buyMethod: "할부",
    source: "카톡채널",
    channel: "당직",
    age: "40대",
    gender: "남",
    firstContact: ago(25),
    nextContact: ahead(0),
    contractDate: ago(2),
    scheduledDelivery: ahead(14),
  },
  {
    id: "m8",
    name: "오예린",
    phone: "010-9920-1144",
    stage: "contract",
    stageRaw: "계약진행",
    heat: "warm",
    rank: "A",
    grade: "VIP",
    salesStatus: "계약고객",
    vehicleClass: "GLE-Class",
    vehicleInterest: "GLE 450 AMG",
    budget: "1.8억",
    criticalFactor: "할인율 / 현물할인",
    buyMethod: "운용리스",
    source: "전화·문자",
    channel: "고객소개",
    age: "50대",
    gender: "여",
    firstContact: ago(30),
    nextContact: ago(1),
    contractDate: ago(5),
    scheduledDelivery: ahead(30),
    exteriorColor: "옵시디언 블랙",
    notes: "법인. 결정권자 미팅 일정 잡아야.",
  },
  {
    id: "m9",
    name: "송재민",
    phone: "010-2387-5503",
    stage: "delivered",
    stageRaw: "출고완료",
    heat: "warm",
    rank: "A",
    grade: "A",
    salesStatus: "출고고객",
    vehicleClass: "C-Class",
    vehicleInterest: "C200 Avantgarde",
    budget: "7,800만",
    buyMethod: "할부",
    source: "카톡채널",
    channel: "유튜브",
    age: "30대",
    gender: "남",
    firstContact: ago(45),
    nextContact: ahead(0),
    contractDate: ago(15),
    deliveredDate: ago(1),
    deliveredModel: "C200 Avantgarde",
    exteriorColor: "카바나이트 블루",
    carNumber: "12가 3456",
    finalResult: "출고성공",
  },
  {
    id: "m10",
    name: "조성민",
    phone: "010-1573-9920",
    stage: "delivered",
    stageRaw: "출고완료",
    heat: "warm",
    rank: "B",
    grade: "VIP",
    salesStatus: "출고고객",
    vehicleClass: "Maybach S-Class",
    vehicleInterest: "S580 Maybach",
    budget: "2.5억",
    buyMethod: "현금",
    source: "전화·문자",
    channel: "고객소개",
    age: "60대+",
    gender: "남",
    contractDate: ago(20),
    deliveredDate: ago(0),
    deliveredModel: "S580 Maybach",
    exteriorColor: "마그네타이트 블랙",
    finalResult: "출고성공",
  },
  {
    id: "m11",
    name: "양서윤",
    phone: "010-3309-1144",
    stage: "aftercare",
    stageRaw: "출고후관리",
    heat: "warm",
    rank: "B",
    grade: "A",
    salesStatus: "출고고객",
    vehicleClass: "GLE-Class",
    vehicleInterest: "GLE 450 4MATIC",
    deliveredDate: ago(30),
    nextContact: ahead(0),
    finalResult: "출고성공",
    age: "40대",
    notes: "D+30 만족도 콜 예정.",
  },
  {
    id: "m12",
    name: "홍찬영",
    phone: "010-6608-2237",
    stage: "aftercare",
    stageRaw: "출고후관리",
    heat: "cold",
    rank: "C",
    grade: "A",
    salesStatus: "출고고객",
    vehicleClass: "EQS",
    vehicleInterest: "EQS 450",
    deliveredDate: ago(180),
    nextContact: ahead(0),
    finalResult: "출고성공",
    notes: "D+180 — 액세서리 / 추천 차량 안내 시점.",
  },
  {
    id: "m13",
    name: "임수빈",
    phone: "010-5577-2890",
    stage: "long_touch",
    stageRaw: "장기터치",
    heat: "cold",
    rank: "C",
    grade: "B",
    salesStatus: "잠재고객",
    vehicleClass: "GLC-Class",
    vehicleInterest: "GLC 300 4MATIC",
    budget: "1.0억",
    source: "구글폼",
    channel: "블로그",
    firstContact: ago(120),
    nextContact: ahead(30),
    notes: "내년 봄 구매 예정. 분기별 리텐션.",
  },
  {
    id: "m14",
    name: "전미래",
    phone: "010-9920-7752",
    stage: "lost",
    stageRaw: "이탈관리",
    heat: "unknown",
    rank: "unknown",
    grade: "F",
    salesStatus: "이탈",
    vehicleClass: "GLC-Class",
    vehicleInterest: "GLC 300 4MATIC",
    competitor: "BMW X3",
    finalResult: "경쟁사이탈",
    firstContact: ago(60),
    nextContact: ago(45),
    notes: "BMW X3 계약. 재방문 가능성 6개월 후.",
  },
];

export const MOCK_CUSTOMERS: Customer[] = RAW_MOCKS.map((m) => ({
  ...m,
  dn: m.dn ?? {},
  logIds: m.logIds ?? [],
  scheduleIds: m.scheduleIds ?? [],
}));
