import type { Customer } from "./types";

const today = new Date();
function ago(days: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() - days);
  return d.toISOString().slice(0, 10);
}
function ahead(days: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "m1",
    name: "박태윤",
    honorific: "고객님",
    vehicle: "GLE 450 4MATIC",
    trim: "AMG Line",
    color: "옵시디언 블랙",
    phone: "010-2841-7733",
    stage: "lead",
    timeframe: "1개월 내",
    source: "네이버 검색",
    lastContactDate: ago(0),
    nextActionLabel: "첫 통화 후 자료 발송",
    nextActionDue: ahead(1),
    notes: "법인 차량 검토. 사이즈 우선.",
  },
  {
    id: "m2",
    name: "이서연",
    honorific: "고객님",
    vehicle: "E300 4MATIC",
    trim: "Exclusive",
    phone: "010-9921-4408",
    stage: "lead",
    source: "지인소개",
    lastContactDate: ago(2),
    nextActionLabel: "관심 모델 카탈로그 발송",
    nextActionDue: ago(0),
    notes: "프로모션 문의 — 이번달 출고 가능?",
  },
  {
    id: "m3",
    name: "정현우",
    honorific: "대표님",
    vehicle: "S580 4MATIC",
    trim: "Long",
    color: "셀레나이트 그레이",
    phone: "010-3372-1190",
    stage: "consult",
    budget: "2.0억",
    timeframe: "2개월",
    decisionMaker: "본인",
    issues: "법인 vs 개인 명의",
    source: "전시장 방문",
    lastContactDate: ago(3),
    nextActionLabel: "리스 견적 비교표 전달",
    nextActionDue: ahead(2),
    history: [
      { date: ago(7), type: "전화", note: "1차 상담. 후속 자료 요청." },
      { date: ago(3), type: "방문", note: "전시장 시승 — S580 대비 EQS 검토." },
    ],
  },
  {
    id: "m4",
    name: "최유진",
    honorific: "고객님",
    vehicle: "EQE 350 4MATIC",
    trim: "AMG Line",
    phone: "010-1188-2370",
    stage: "consult",
    budget: "1.2억",
    source: "유튜브",
    lastContactDate: ago(8),
    nextActionLabel: "리텐션 콜 — 식어가는 중",
    nextActionDue: ago(1),
    notes: "1주 무응답.",
  },
  {
    id: "m5",
    name: "강지현",
    honorific: "고객님",
    vehicle: "GLC 300 4MATIC Coupe",
    trim: "AMG Line",
    color: "폴라 화이트",
    phone: "010-7752-3098",
    stage: "quote",
    budget: "9,200만",
    timeframe: "3주 내",
    source: "인스타그램",
    lastContactDate: ago(1),
    nextActionLabel: "시승 예약 (~5/3)",
    nextActionDue: ahead(5),
    history: [
      { date: ago(5), type: "전화", note: "GLC vs X3 비교 요청." },
      { date: ago(1), type: "메시지", note: "견적서 확인 — 색상 변경 검토." },
    ],
  },
  {
    id: "m6",
    name: "윤태영",
    honorific: "고객님",
    vehicle: "CLE 53 Cabriolet",
    trim: "AMG",
    phone: "010-4408-5511",
    stage: "quote",
    budget: "1.5억",
    timeframe: "출시 직후",
    source: "블로그",
    lastContactDate: ago(2),
    nextActionLabel: "시승 후 후속 — 골든타임 7일",
    nextActionDue: ahead(4),
  },
  {
    id: "m7",
    name: "한도윤",
    honorific: "고객님",
    vehicle: "E200 4MATIC",
    trim: "Avantgarde",
    phone: "010-6629-4471",
    stage: "negotiate",
    budget: "8,500만",
    timeframe: "2주 내",
    decisionMaker: "본인+배우자",
    issues: "트레이드인 가격",
    lastContactDate: ago(1),
    nextActionLabel: "트레이드인 평가 회신",
    nextActionDue: ahead(0),
  },
  {
    id: "m8",
    name: "오예린",
    honorific: "팀장님",
    vehicle: "GLE 450 AMG",
    trim: "AMG",
    color: "옵시디언 블랙",
    phone: "010-9920-1144",
    stage: "negotiate",
    budget: "1.8억",
    timeframe: "이번 분기",
    decisionMaker: "법인 대표",
    issues: "할인율 / 현물할인",
    lastContactDate: ago(4),
    nextActionLabel: "최종 할인안 컨펌",
    nextActionDue: ago(1),
    notes: "3차 협상. 결정권자 미팅 일정 잡아야.",
  },
  {
    id: "m9",
    name: "송재민",
    honorific: "고객님",
    vehicle: "C200 4MATIC",
    trim: "Avantgarde",
    color: "카바나이트 블루",
    phone: "010-2387-5503",
    stage: "contract",
    budget: "7,800만",
    lastContactDate: ago(0),
    nextActionLabel: "계약서 사본 송부",
    nextActionDue: ahead(0),
    history: [
      { date: ago(0), type: "방문", note: "계약 체결, 계약금 입금 완료." },
    ],
  },
  {
    id: "m10",
    name: "조성민",
    honorific: "대표님",
    vehicle: "S580 Maybach",
    trim: "Maybach",
    color: "마그네타이트 블랙",
    phone: "010-1573-9920",
    stage: "schedule",
    budget: "2.5억",
    lastContactDate: ago(2),
    nextActionLabel: "탁송 일정 확정",
    nextActionDue: ahead(3),
  },
  {
    id: "m11",
    name: "허다인",
    honorific: "고객님",
    vehicle: "GLC 300 4MATIC",
    trim: "AMG Line",
    color: "폴라 화이트",
    phone: "010-8801-3372",
    stage: "schedule",
    lastContactDate: ago(1),
    nextActionLabel: "보험 가입 안내",
    nextActionDue: ahead(1),
  },
  {
    id: "m12",
    name: "신우진",
    honorific: "고객님",
    vehicle: "E300 4MATIC",
    trim: "Exclusive",
    color: "셀레나이트 그레이",
    phone: "010-4471-9920",
    stage: "delivered",
    lastContactDate: ago(1),
    nextActionLabel: "D+1 인도 점검 콜",
    nextActionDue: ahead(0),
    history: [
      { date: ago(1), type: "출고", note: "차량 인도 완료. 등록증 전달." },
    ],
  },
  {
    id: "m13",
    name: "양서윤",
    honorific: "고객님",
    vehicle: "GLE 450 4MATIC",
    trim: "AMG Line",
    phone: "010-3309-1144",
    stage: "aftercare",
    lastContactDate: ago(30),
    nextActionLabel: "D+30 점검 — 만족도 콜",
    nextActionDue: ahead(0),
  },
  {
    id: "m14",
    name: "홍찬영",
    honorific: "고객님",
    vehicle: "EQS 450",
    trim: "AMG Line",
    phone: "010-6608-2237",
    stage: "aftercare",
    lastContactDate: ago(180),
    nextActionLabel: "D+180 — 액세서리 / 추천 차량",
    nextActionDue: ahead(0),
  },
  {
    id: "m15",
    name: "전미래",
    honorific: "고객님",
    vehicle: "GLC 300 4MATIC",
    phone: "010-9920-7752",
    stage: "lost",
    lastContactDate: ago(45),
    nextActionLabel: "재접촉 보류 — 경쟁사 이동",
    notes: "BMW X3 계약. 재방문 가능성 6개월 후.",
  },
];
